name: Lint

on:
  push:

jobs:
  pint:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
      - name: Install dependencies
        run: composer install
      - name: Run laravel pint and rector
        run: composer lint
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply pint changes
